<?php
/**
 * Responsive Blog Options
 *
 * A class that extends the core option class and adds more functionality
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

Class Responsive_Blog_Options {

	/**
	 * Default list of post categories static function
	 *
	 * @return array
	 */
	public static function responsive_blog_posts()
	{

	// Pull all post categories
		$options_post_cats = array();
		$rblog_post_categories   = get_terms( 'category', array( 'hide_empty' => 0 ) );
		
			foreach ( $rblog_post_categories as $rblog_cat ) {
				$options_post_cats[$rblog_cat->slug] = $rblog_cat->name;
			}
		
		return $options_post_cats;
	}


	/**
	 * Default list of testimonial post categories static function
	 *
	 * @return array
	 */
	public static function responsive_testimonial_posts()
	{

	// Pull all testimonial categories
		$options_testimonial_cats = array();
		$testimonial_categories   = get_terms( 'testimonial_categories', array( 'hide_empty' => 0 ) );
		
			foreach ( $testimonial_categories as $testimonial_cat ) {
				$options_testimonial_cats[$testimonial_cat->slug] = $testimonial_cat->name;
			}
		
		return $options_testimonial_cats;
	}
} // end of class Responsive_Blog_Options
