name: Deploy to dev

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - name: Install dependencies
              run: |
                  cd wp-content/themes/mediasanctuary
                  npm install

            - name: Build
              run: |
                  cd wp-content/themes/mediasanctuary
                  npm run build

            - name: Sync
              env:
                  dest: "devmediasan@claudette.mayfirst.org:/home/members/nyma/sites/dev.mediasanctuary.org/web/wp-content/"
              run: |
                  echo "${{secrets.DEPLOY_KEY}}" > deploy_key
                  chmod 600 ./deploy_key
                  rsync \
                    --rsh='ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
                    --delete \
                    --checksum \
                    --recursive \
                    --verbose \
                    --human-readable \
                    --filter='P uploads' \
                    --exclude wp-content/uploads \
                    ./wp-content/ ${{env.dest}}
